---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

                                               # Andersen Darling test to find optimal point in the past
```{r}
library(PMCMRplus)

andersen_darling_stocks_test <- function(data,tau_digit){            # Тест Андерсена - Дарлинга
  tau=tau_digit
  param=1
  n=round(nrow(data)/tau,0)
  for (j in 2:ncol(data)){
     matr <- matrix(ncol=5,nrow=n)
     price <- as.vector(data[,j])
     for (i in 4:(n-4)){
           k <- i*tau
           p <- length(price)
           y <- price[0:k]
           z <- price[(k+1):p]
           g <- factor(x=c(rep(1,k),rep(2,(p-k))),labels=c("fisrt_time","second_time"))
           dat1 <- data.frame(g=g,x=c(y,z))
           test <- adKSampleTest(x~g,data=dat1)
           c=c(colnames(data)[j],i*tau,as.vector(test$estimate)[1],as.vector(as.numeric(test$estimate))[2],as.vector(as.numeric(test$p.value))[1])
           matr[i,] <- c}
     matr <- matr[-c(1:3),]
     matr <- matr[-c((nrow(matr)-3):nrow(matr)),]
     matr <- data.frame(matr)
     colnames(matr) <- c("Stock","Itau","Akm2","sigma","p_value")
     matr$Akm2 <- as.numeric(as.character(matr$Akm2))}
     return(matr)}

```


                                                Volatility that is estimated using results of the Andersen Darling test
```{r}

find_volatility <- function(ticker,start,end){
  hist_prices <- tryCatch(getSymbols(ticker, src = 'yahoo', from = start ,to = end, auto.assign = F),error=function(e){print(paste("failed to   download",ticker))})             # download history prices
  hist_prices <- as.data.frame(hist_prices[,c(paste0(ticker,".Open"),paste0(ticker,".Close"))])    # select columns
  dates <- as.Date(row.names(hist_prices))
  hist_prices <- cbind(dates,hist_prices)        
  hist_prices <- hist_prices[,c(1,3)]
  
  m <- andersen_darling_stocks_test(hist_prices,tau_digit = 10)                       # find result of the test with step =10 days (tau)
  m <- m[order(m$Akm2,decreasing = TRUE),]
  hist_prices <- hist_prices[as.numeric(as.character(m$Itau[1])):nrow(hist_prices),]  # select time point which has the biggest Akm2
  
  returns <- c(0)
  for(i in 2:nrow(hist_prices)){
    returns[i] <- (hist_prices[i,2]-hist_prices[(i-1),2])/hist_prices[(i-1),2]        # find returns for estimated time period
  }
  return(sd(returns))                                                                 # return sd for estimated returns
  
}

```


                                                    
```{r}
library(RQuantLib)   
library(quantmod)    
library(lubridate)   

calculation_of_position <- function(ticker,start_date,end_date,hist_number_of_years,Free_rate,strike){
  
  # 1) загружаем данные,создаем дополнительные столбцы: страйк цена, время до экспирации опциона (в годах)
  data_price <- tryCatch(getSymbols(ticker, src = 'yahoo', from = as.Date(start_date),to=end_date, auto.assign = F),error=function(e){print(paste("failed to   download",'TSLA'))})
  data_price <- as.data.frame(data_price[,c(paste0(ticker,".Open"),paste0(ticker,".Close"))])
  dates <- as.Date(row.names(data_price))
  years_until_expiration <- as.numeric(as.Date(end_date)-dates)/as.numeric(as.Date(end_date)-as.Date(start_date))  # расчет количества времени до экспирации опциона

  data_price <- as.data.frame(data_price[,c(paste0(ticker,".Open"),paste0(ticker,".Close"))])
  data_price <- cbind(dates,data_price)
  data_price <- cbind(data_price,years_until_expiration)
  data_price$strike_price <- data_price[1,2]*strike                            # расчет цены страйк опциона
  colnames(data_price) <- c('Date','current_price_open','current_price_close','years_until_expiration','strike')
  
  # 2) Для каждого рассчитываем цену опциона и дельту опциона CALL используя функицю EuropeanOption
  current_call_option_value <- c()
  current_call_delta <- c()
  #current_put_option_value <- c()
  #current_put_delta <- c()
  Volatility=0
  for( i in 1:nrow(data_price)){
    # find correct Volatility using Andersen-Darling test
    
    if(i%%20==0 | i==1){
      Volatility <- find_volatility(ticker,start = as.Date(start_date)-years(hist_number_of_years),end=as.Date(data_price$Date[i]))
      print(paste(i,Volatility))            # recalculate volatility every 20 days using information fromAndersen Darling test
    }
    # calculate characteristics of call option 
    m_call=EuropeanOption(type='call', underlying=data_price$current_price_close[i], strike=data_price$strike[i],
                   riskFreeRate=Free_rate, maturity=data_price$years_until_expiration[i], volatility=Volatility,dividendYield = 0)
    #m_put=EuropeanOption(type='put', underlying=data_price$current_price_close[i], strike=data_price$strike[i],
    #               riskFreeRate=Free_rate, maturity=data_price$years_until_expiration[i], volatility=Volatility,dividendYield = 0)

    current_call_option_value[i] <- as.numeric(m_call[1])   # save option value
    current_call_delta[i] <- as.numeric(m_call[2])          # save option delta
    #current_put_option_value[i] <- as.numeric(m_put[1])
    #current_put_delta[i] <- as.numeric(m_put[2])
    
  }
  data_price <- cbind(data_price,current_call_option_value)
  data_price <- cbind(data_price,current_call_delta)
  #data_price <- cbind(data_price,current_put_option_value)
  #data_price <- cbind(data_price,current_put_delta)
  
  # find opertion type: No opertaion if delta<0.5; Buy stocks if delta>0.5; Sell stocks if decreased
  operation_type <- c('No operation')
  for(i in 2:nrow(data_price)){
    if(data_price$current_call_delta[i]>=0.5){    # если delta>=0.5 покупаем акции компании, иначе ничего не делаем
        if(data_price$current_call_delta[i]<data_price$current_call_delta[i-1]){
          operation_type[i] <- 'Sell'
      }
        else{
          operation_type[i] <- 'Buy'
      }}
    else{
      operation_type[i] <- operation_type[i-1] 
      }
  }
  data_price <- cbind(data_price,operation_type)

  # find how much stocks should be bought for every day
  stocks_to_buy <- c()
  to_buy=0
  for(i in 1:nrow(data_price)){
    if(data_price$operation_type[i]=='No operation'){
      stocks_to_buy[i]=0
    }
    else if(data_price$operation_type[i]=='Buy'){
      stocks_to_buy[i] <- max(data_price$current_call_delta[i],to_buy)          # how much stocks should by bought
      to_buy <-  max(to_buy,data_price$current_call_delta[i])
    }
    else{
      stocks_to_buy[i] <- to_buy-(data_price$current_call_delta[i-1]-data_price$current_call_delta[i])
      to_buy <-  to_buy-(data_price$current_call_delta[i-1]-data_price$current_call_delta[i])
    }
    print(to_buy)
  }
  data_price <- cbind(data_price,stocks_to_buy)
  return(data_price)
}
```


```{r}
result <- calculation_of_position(ticker = 'PHM',start_date = '2019-12-31',end_date = '2020-12-31',Free_rate = 0.01,strike = 1.1,hist_number_of_years = 3)
library(ggplot2)
```

